### ISSUE TITLE
Publishing to elm package repository

### ISSUE THREAD

**Issue by 3rwww1** [toburger/elm-xml-parser#4]
Hi, do you have any plans for publishing this to the elm package repository ?

**Comment by toburger** [comment]
Hi Erwan, to be honest I'm not sure.

This project started basically as an experiment because I was interested in learning parser combinators and parsing XML seemed an interesting use case.

There is still some considerable amount of homework to be done before this package is ready for publishing:
- [ ] Project structure overhaul
- [ ] Unit Tests
- [ ] Performance?

The other thing is that at the moment I'm more involved into backend programming and not coding in elm.

**Comment by stkb** [comment]
Came across this project while looking for an xml parser in Elm and was surprised that there wasn't already one in the package repository.

I understand desire to only want to publish a quality product, but given the complete absence of Elm alternatives I really think the work done here should be published, after a maybe just a little more (eg I found after trying to use it that it doesn't support processing instructions). Yes you can use x2js through ports but it's nicer to be able to just import an Elm package.

I don't think the API matters too much for a v1.0; people can suggest changes after using it. Nor does performance; that can come later and people can use the js-land solution instead if they need that.

I've upgraded the module to Elm 0.18 in my fork and will be happy to submit that as a PR, as well as some other work (like adding tests). I can also take the project off your hands if you'd rather that.

**Comment by toburger** [comment]
Hi @stkb, you are very welcome to help me out!
I think it's best to hand you over the project because ATM I have not really the time to maintain it.
Sorry, I wish I could code more in elm soon...

**Comment by toburger** [comment]
Elm package available [here](https://package.elm-lang.org/packages/jinjor/elm-xml-parser/latest/)
Should have been closed years before... 😄
